PAD_TOKEN = "<pad>"
SPACE_TOKEN = "<s>"
TAB_TOKEN = "<t>"
BREAK_TOKEN = "<b>"

KERN_LINE_BREAK = "\n"
KERN_TAB = "\t"
KERN_SPACE = " "
KERN_MIDDLE_DOT = "\u00b7"

BEKRN_EXTENSION = ".bekrn"
JPG_EXTENSION = ".jpg"
DISTORTED_IMAGE_SUFFIX = "_distorted"
DISTORTED_IMAGE_HEIGHT = 256

ENCODER_HEIGHT_REDUCTION = 16
ENCODER_WIDTH_REDUCTION = 8
ENCODER_OUTPUT_CHANNELS = 512
